### ISSUE TITLE
GPU monitoring

### ISSUE THREAD

**Issue by NasonZ** [hakandundar34coding/mini-system-monitor#1]
Is it possible to customise the visualisation? I would like to have my NVIDIA GPU metrics (temp and memory) in place of the network usage.

**Comment by hakandundar34coding** [comment]
New features are not added to Mini System Monitor.
For more features, you can use [System Monitoring Center](https://github.com/hakandundar34coding/system-monitoring-center).
But currently, there are no plans for adding GPU information to Summary tab of System Monitoring Center for lower CPU usage. It may be optional in new versions.
